name: Arcana
description: Arcana template for Jekyll
paginate: 10

title: "yejiejie.github.io 开展个人学习网络"
description: "在更辽阔的（全球资讯网）世界感觉更自在地体验及学习"
affiliation: "中山大学南方学院 <a href = 'http://wcy.nfu.edu.cn/zh/教学教务/培养方案/网络与新媒体/'>网络与新媒体</a> 培养方案核心课程学期作品，由 <a href='http://wcy.nfu.edu.cn/zh/学院概况/师资队伍/廖汉腾/'>廖汉腾副教授</a> 指导"
